/// Lớp tiện ích giúp sửa lỗi encoding tiếng Việt
class VietnameseEncodingMaps {
  /// Danh sách các ký tự có thể gây lỗi encoding
  static final List<String> problematicSequences = [
    'Ã', 'Ä', 'Æ', 'áº', 'á»', 'Å©', 'Ãª', 'Ã¡', 'Ã ', 'Ã£',
    'Æ°', 'Æ¡', 'Ã´', 'Ã¢', 'Äƒ', 'Ã½', 'Ã³', 'Ã²', 'Ã¨', 'Ã©',
    'Å', 'Ã­', 'Ã¬', 'Ã¹', 'Ãº',
  ];

  /// Kiểm tra xem một chuỗi có vấn đề encoding không
  static bool hasEncodingIssues(String text) {
    if (text.isEmpty) return false;
    
    for (final seq in problematicSequences) {
      if (text.contains(seq)) {
        return true;
      }
    }
    return false;
  }

  /// Sửa lỗi encoding tiếng Việt
  static String fixVietnameseEncoding(String text) {
    if (text.isEmpty) return text;
    
    // Kiểm tra nhanh xem có lỗi không
    if (!hasEncodingIssues(text)) return text;
    
    String result = text;
    
    // Áp dụng các quy tắc thay thế
    _simpleReplacements.forEach((key, value) {
      result = result.replaceAll(key, value);
    });
    
    // Xử lý thêm một lần nữa để bắt các trường hợp lồng nhau
    _simpleReplacements.forEach((key, value) {
      result = result.replaceAll(key, value);
    });
    
    return result;
  }

  /// Bảng ánh xạ đơn giản cho các ký tự tiếng Việt
  static final Map<String, String> _simpleReplacements = {
    // Nguyên âm với dấu
    'Ã¡': 'á',
    'Ã ': 'à',
    'áº£': 'ả',
    'Ã£': 'ã',
    'áº¡': 'ạ',
    'Ã¢': 'â',
    'áº¥': 'ấ',
    'áº§': 'ầ',
    'áº©': 'ẩ',
    'áº«': 'ẫ',
    'áº­': 'ậ',
    'Äƒ': 'ă',
    'áº¯': 'ắ',
    'áº±': 'ằ',
    'áº³': 'ẳ',
    'áºµ': 'ẵ',
    'áº·': 'ặ',
    'Ã©': 'é',
    'Ã¨': 'è',
    'áº»': 'ẻ',
    'áº½': 'ẽ',
    'áº¹': 'ẹ',
    'Ãª': 'ê',
    'áº¿': 'ế',
    'á»': 'ề',
    'á»ƒ': 'ể',
    'á»…': 'ễ',
    'á»‡': 'ệ',
    'Ã­': 'í',
    'Ã¬': 'ì',
    'á»‰': 'ỉ',
    'Ä©': 'ĩ',
    'á»‹': 'ị',
    'Ã³': 'ó',
    'Ã²': 'ò',
    'á»': 'ỏ',
    'Ãµ': 'õ',
    'á»': 'ọ',
    'Ã´': 'ô',
    'á»': 'ố',
    'á»"': 'ồ',
    'á»•': 'ổ',
    'á»—': 'ỗ',
    'á»™': 'ộ',
    'Æ¡': 'ơ',
    'á»›': 'ớ',
    'á»': 'ờ',
    'á»Ÿ': 'ở',
    'á»¡': 'ỡ',
    'á»£': 'ợ',
    'Ãº': 'ú',
    'Ã¹': 'ù',
    'á»§': 'ủ',
    'Å©': 'ũ',
    'á»¥': 'ụ',
    'Æ°': 'ư',
    'á»©': 'ứ',
    'á»«': 'ừ',
    'á»­': 'ử',
    'á»¯': 'ữ',
    'á»±': 'ự',
    'Ã½': 'ý',
    'á»³': 'ỳ',
    'á»·': 'ỷ',
    'á»¹': 'ỹ',
    'á»µ': 'ỵ',
    'Ä': 'đ',
    
    // Chữ hoa
    'Ã': 'Á',
    'Ã€': 'À',
    'áº¢': 'Ả',
    'Ãƒ': 'Ã',
    'áº ': 'Ạ',
    'Ã‚': 'Â',
    'áº¤': 'Ấ',
    'áº¦': 'Ầ',
    'áº¨': 'Ẩ',
    'áºª': 'Ẫ',
    'áº¬': 'Ậ',
    'Ä‚': 'Ă',
    'áº®': 'Ắ',
    'áº°': 'Ằ',
    'áº²': 'Ẳ',
    'áº´': 'Ẵ',
    'áº¶': 'Ặ',
    'Ã‰': 'É',
    'Ãˆ': 'È',
    'áºº': 'Ẻ',
    'áº¼': 'Ẽ',
    'áº¸': 'Ẹ',
    'ÃŠ': 'Ê',
    'áº¾': 'Ế',
    'á»€': 'Ề',
    'á»‚': 'Ể',
    'á»„': 'Ễ',
    'á»†': 'Ệ',
    'Ã': 'Í',
    'ÃŒ': 'Ì',
    'á»ˆ': 'Ỉ',
    'Ä¨': 'Ĩ',
    'á»Š': 'Ị',
    'Ã"': 'Ó',
    'Ã¨': 'Ò',
    'á»Ž': 'Ỏ',
    'Ã•': 'Õ',
    'á»Œ': 'Ọ',
    'Ã"': 'Ô',
    'á»': 'Ố',
    'á»"': 'Ồ',
    'á»"': 'Ổ',
    'á»–': 'Ỗ',
    'á»˜': 'Ộ',
    'Æ ': 'Ơ',
    'á»š': 'Ớ',
    'á»œ': 'Ờ',
    'á»ž': 'Ở',
    'á» ': 'Ỡ',
    'á»¢': 'Ợ',
    'Ãš': 'Ú',
    'Ã™': 'Ù',
    'á»¦': 'Ủ',
    'Å¨': 'Ũ',
    'á»¤': 'Ụ',
    'Æ¯': 'Ư',
    'á»¨': 'Ứ',
    'á»ª': 'Ừ',
    'á»¬': 'Ử',
    'á»®': 'Ữ',
    'á»°': 'Ự',
    'Ã': 'Ý',
    'á»²': 'Ỳ',
    'á»¶': 'Ỷ',
    'á»¸': 'Ỹ',
    'á»´': 'Ỵ',
    'Ä': 'Đ',
    
    // Các từ thường gặp
    'há»c': 'học',
    'trÆ°á»ng': 'trường',
    'tiáº¿ng': 'tiếng',
    'viá»‡t': 'việt',
    'ngÆ°á»i': 'người',
    'phÃ²ng': 'phòng',
    'cá»­a': 'cửa',
    'vÃ o': 'vào',
    'giÃ¡o': 'giáo',
    'dá»‹ch': 'dịch',
    'tá»«': 'từ',
    'Viá»‡t': 'Việt',
    'cÃ´': 'cô',
    'ÄÃ¢y': 'đây',
    'ÄÃ³': 'đó',
    'khÃ´ng': 'không',
    'ngÃ y': 'ngày',
    'thÃ¡ng': 'tháng',
    'nÄƒm': 'năm',
    'sÃ¡ch': 'sách',
    'há»i': 'hỏi',
    'tÃªn': 'tên',
    'sá»': 'số',
    'TÃ´i': 'Tôi',
    'Äá»ng': 'đồng',
    'ngá»¯': 'ngữ',
    'tháº¿': 'thế',
    'nÃ o': 'nào',
    'á»«ng': 'ừng',
    'ná»¯a': 'nữa',
    'vÃ¬': 'vì',
    'vá»›i': 'với',
    'láº¡i': 'lại',
    'quá»c': 'quốc',
    'há»™i': 'hội',
    'Äá»c': 'đọc',
    'viáº¿t': 'viết',
    'tráº£': 'trả',
    'láº¥y': 'lấy',
    'má»›i': 'mới',
    'nhiá»u': 'nhiều',
    'cÃ²n': 'còn',
    'cÃ¡c': 'các',
    'Äiá»u': 'điều',
    'Äá»u': 'đều',
    'Äáº¿n': 'đến',
    'nÃ³i': 'nói',
    'láº§n': 'lần',
    'cáº§n': 'cần',
    'lÃ m': 'làm',
    'bá»‹': 'bị',
    'báº¯t': 'bắt',
    'Äáº§u': 'đầu',
    'tháº§y': 'thầy',
    'cÃ´ng': 'công',
    'viá»‡c': 'việc',
    'cá»§a': 'của',
    'báº£n': 'bản',
    'gá»­i': 'gửi',
    'Äá»i': 'đợi',
    'biáº¿t': 'biết',
    'xÃ¢y': 'xây',
    'dá»±ng': 'dựng',
    'tá»t': 'tốt',
    'chÃºng': 'chúng',
    'mÃ¬nh': 'mình',
    'má»™t': 'một',
    'hai': 'hai',
    'nÆ°á»›c': 'nước',
    
    // Các cụm từ
    'tiáº¿ng Viá»‡t': 'tiếng Việt',
    'tiáº¿ng Anh': 'tiếng Anh',
    'tá»« Äiá»ƒn': 'từ điển',
    'há»c sinh': 'học sinh',
    'trÆ°á»ng há»c': 'trường học',
    'giÃ¡o dá»¥c': 'giáo dục',
    'Äáº¡i há»c': 'đại học',
    'chÃ­nh phá»§': 'chính phủ',
    'cÃ´ng nghá»‡': 'công nghệ',
    'thÃ´ng tin': 'thông tin',
    'báº£n quyá»n': 'bản quyền',
    'sá»± kiá»‡n': 'sự kiện',
    'thÃ nh phá»': 'thành phố',
    'Äiá»n thoáº¡i': 'điện thoại',
    'mÃ¡y tÃ­nh': 'máy tính',
    'quá»c gia': 'quốc gia',
    'giao thÃ´ng': 'giao thông',
    'xÃ£ há»™i': 'xã hội',
    'vÄƒn hÃ³a': 'văn hóa',
    'kinh táº¿': 'kinh tế',
    'y táº¿': 'y tế',
    'ngÃ¢n hÃ ng': 'ngân hàng',
    'cÃ´ng ty': 'công ty',
    'doanh nghiá»‡p': 'doanh nghiệp',
    'quáº£n lÃ½': 'quản lý',
    'Äiá»n áº£nh': 'điện ảnh',
    'Äáº¹p': 'đẹp',
    'bá»™ phim': 'bộ phim',
    'nghá» thuáº­t': 'nghệ thuật',
    'ÄÆ¡n giáº£n': 'đơn giản',
    'phá»©c táº¡p': 'phức tạp',
    'pháº§n má»m': 'phần mềm',
    'thÆ° viá»‡n': 'thư viện',
    'trang web': 'trang web',
    'phÃ¡t triá»ƒn': 'phát triển',
    'á»©ng dá»¥ng': 'ứng dụng',
    'thiáº¿t káº¿': 'thiết kế',
    'nguyÃªn táº¯c': 'nguyên tắc',
    'cá»™ng Äá»"ng': 'cộng đồng',
    'nháº­n biáº¿t': 'nhận biết',
    'thá»i gian': 'thời gian',
    'tá»i Æu': 'tối ưu',
    'hiá»ƒu quáº£': 'hiểu quả',
    'pháº£n há»"i': 'phản hồi',
  };
} 