// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTdWXFP3jgU-w2GgFslrWpFxiJclZ7h0k',
    appId: '1:385592852853:android:38ddad8829b4df8202d33c',
    messagingSenderId: '385592852853',
    projectId: 'la-english',
    storageBucket: 'la-english.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSR_XzZX3fVT3CU7luKXc2AvpWe42I0k0',
    appId: '1:385592852853:ios:0f7d0ece3bca4bc102d33c',
    messagingSenderId: '385592852853',
    projectId: 'la-english',
    storageBucket: 'la-english.firebasestorage.app',
    iosBundleId: 'com.ppclink.ios.timnha24h',
  );
}
